### ISSUE TITLE
I think there may be a bug with fast_fail false and more complex schemas

### ISSUE THREAD

**Issue by Heiko-san** [jamesturk/validictory#100]
Hi,

I think there may be a bug with fast_fail false and more complex schemas.
I tested validictory (1.0.2 with python 2.7.9 on debian 8.5) using it successfully, getting errors like 3 errors found and then a list, as expected.

However after I started using a more complex schema I always got a schema exception without finding something wrong with my schema, actually after removing fast_fail=False everything worked as expected (of course with only one error reported at a time).

Exception:
validictory.validator.SchemaError: Type for field 'foo' must be 'dict', got: 'bool'

The full exception stack trace I got and example code / data / schema that can reproduce the exception can be found at this stackoverflow post: http://stackoverflow.com/questions/38771938/how-to-ensure-only-patternproperties-that-match-a-particular-pattern

I'm really not sure if I did something wrong or it is really a bug, but it seams like a bug to me(Since I got the thinking that the schema should be constant and "foo" in my example isn't even part of the schema but the data), please correct me if I missed something.

**Comment by jamesturk** [comment]
Can you show an example (or test case) with this behavior?  Glad to look into it

**Comment by bmdemouser** [comment]
It can be found at the linked stackoverflow post, but here it is:
```
import validictory

data = {
    'tests': {
        'default': {
            'timeout_status': 'amber',
            'sensor': 'http',
            'modules': {
                'statuscode': {'200': 'red'}
            }
        },
        'tgoogle': {
            'sensor': 'http',
            'modules': {
                'statuscode': {
                    '200': 'green',
                    'foo': 'bar',
                },
            },
            'timeout_status': 'amber'
        }
    }, 
    # ... more besides key tests
}

SCHEMA = {
    'type': 'object',
    'properties': {
        'tests': {
            'additionalProperties': {
                'type': 'object',
                'properties': {
                    'timeout_status': {
                        'enum': ['amber', 'yellow', 'green', 'red'],
                        'type': 'string'
                    }, 
                    'sensor': {
                        'pattern': '^\S+$',
                        'type': 'string'
                    }, 
                    'modules': {
                        'additionalProperties': False,
                        'type': 'object',
                        'properties': {
                            'statuscode': {
                                'additionalProperties': False,
                                'required': False,
                                'type': 'object',
                                'patternProperties': {
                                    '^[0-9x]{3}': {
                                        'enum': ['amber', 'yellow', 'green', 'red'],
                                        'type': 'string',
                                    }
                                }
                            }
                            # ... more available test modules
                        }
                    }
                }
            },
            'type': 'object'
        },
        # ... more besides key tests
    }
}

validictory.validate(data, SCHEMA) #<- this fails as expected at foo
#validictory.validate(data, SCHEMA, fail_fast=False) #<- this throws the exception from below
```

**Comment by Heiko-san** [comment]
Hi, 

another thing that I think isn't really worth another bug ticket:
Because I have to support OS distries from stone age with my project, I happend to test validictory 1.0.2 on python 2.6.
It dies with the Error:
```
Traceback (most recent call last):
  File "./example.helpers.py", line 127, in <module>
    epilog=epilog
  File "/opt/monitoring/pythonlibs/BMStatus.py", line 212, in __init__
    self.load_config(self.options.configfile, False if self.options.configfile is None else True)
  File "/opt/monitoring/pythonlibs/BMStatus.py", line 356, in load_config
    self._validate(config)
  File "/opt/monitoring/pythonlibs/BMStatus.py", line 408, in _validate
    validictory.validate(config, self.confvalidate)
  File "/usr/lib/python2.6/site-packages/validictory/__init__.py", line 43, in validate
    return v.validate(data, schema)
  File "/usr/lib/python2.6/site-packages/validictory/validator.py", line 590, in validate
    self.__validate("data", {"data": data}, schema, '<obj>')
  File "/usr/lib/python2.6/site-packages/validictory/validator.py", line 632, in __validate
    validator(data, fieldname, schema, path, newschema.get(schemaprop))
  File "/usr/lib/python2.6/site-packages/validictory/validator.py", line 285, in validate_properties
    path + '.' + property)
  File "/usr/lib/python2.6/site-packages/validictory/validator.py", line 632, in __validate
    validator(data, fieldname, schema, path, newschema.get(schemaprop))
  File "/usr/lib/python2.6/site-packages/validictory/validator.py", line 319, in validate_items
    '{}[{}]'.format(path, index))
ValueError: zero length field name in format
```
I wouldn't even think about bothering you with python 2.6 if the fix wouldn't be that easy, all it needs is to change line 319 to:
```
'{0}[{1}]'.format(path, index))
```

**Comment by jamesturk** [comment]
SchemaErrors will always fail immediately
